imageType:
  Original: {}

featureClass:
  firstorder: {}
  shape: {}
  glcm: {}
  glrlm: {}
  glszm: {}
  ngtdm: {}
  gldm: {}

setting:
  binWidth: 25
  resampledPixelSpacing: null
  normalize: true
  removeOutliers: true
  interpolator: 'sitkBSpline'
  padDistance: 5
